### ISSUE TITLE
Hello eigenpi，would please give the c code Address of this Algorithm (the old address i found via google can't be opened). Very thanks to you！

### ISSUE THREAD

**Issue by lingkai1** [eigenpi/CS2-CPP#1]

**Comment by eigenpi** [comment]
Hi,
I notices cs2/ code is not available anymore.But I also saw that some people made copies of it.Here is an example:https://github.com/iveney/cs2

Cris.

 ---- Cristinel Ababei 785-312-0223

**Comment by lingkai1** [comment]
Very thanks to you！
